### ISSUE TITLE
Style Transfer Effect no longer working in Paint.net.

### ISSUE THREAD

**Issue by Pixey1974** [patlevin/pdn-styletransfer#3]
File: C:\Program Files\paint.net\Effects\StyleTransferEffect.dll
      Effect Name: PaintDotNet.Effects.ML.StyleTransfer.Plugin.StyleTransferEffect
      Full error message: PaintDotNet.WorkerThreadException: Worker thread threw an exception
 ---> Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:Fail] D:\Repos\onnxruntime\onnxruntime\core\session\inference_session.cc:262 onnxruntime::InferenceSession::InferenceSession result was false. Could not parse model successfully while constructing the inference session

   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(Byte[] modelData, SessionOptions options)
   at PaintDotNet.Effects.ML.StyleTransfer.EffectModel.Reset(Byte[] modelData)
   at PaintDotNet.Effects.ML.StyleTransfer.Plugin.StyleTransferEffect.OnSetRenderInfo(StyleTransferEffectConfigToken newToken, RenderArgs dstArgs, RenderArgs srcArgs)
   at PaintDotNet.Effects.Effect`1.OnSetRenderInfo(EffectConfigToken parameters, RenderArgs dstArgs, RenderArgs srcArgs) in D:\src\pdn\src\Effects.Core\Effects\Effect`1.cs:line 90
   at PaintDotNet.Effects.BackgroundEffectRenderer.ThreadFunction() in D:\src\pdn\src\PaintDotNet\Effects\BackgroundEffectRenderer.cs:line 259
   --- End of inner exception stack trace ---
   at PaintDotNet.Effects.BackgroundEffectRenderer.DrainExceptions() in D:\src\pdn\src\PaintDotNet\Effects\BackgroundEffectRenderer.cs:line 437
   at PaintDotNet.Menus.EffectMenuBase.DoEffect(Effect effect, EffectConfigToken token, Result`1 lazyAllRenderScans, Result`1 lazyRemainingRenderScans, Result`1 lazyClipMaskRenderer, Surface originalSurface, Exception& exception) in D:\src\pdn\src\PaintDotNet\Menus\EffectMenuBase.cs:line 1436

**Comment by patlevin** [comment]
The latest versions are no longer compatible with the plugin. 
I'll look into it over the weekend.

**Comment by Pixey1974** [comment]
Thanks a lot.

**Comment by Bernard-univ** [comment]
Hi. Any news on this front?
I have the same crash using Paint.NET (v 4.3.7). I hope you find the time to fix the problem - I'm really looking forward to using the plugin again

By the way, the setting dialog is not satisfied with the zoom factors on the high resolution display. My 15" screen on my laptop has a resolution of 2560 x 1200 pixels, so I have to set a zoom factor of 150% or 200% to enlarge the menus, icons, etc. for convenience. By 200% enlargement, the dialog box is messed up, you need to guess the UI
![dialog](https://user-images.githubusercontent.com/18291480/212495773-e2a1cfa8-7cea-4d68-8f12-417c6c193f0a.jpg)

**Comment by patlevin** [comment]
Hi, unfortunately the latest PDN version (5.x) would require a complete rewrite at this point and I'm not sure there's enough interest in the plugin to warrant the effort. I'm currently working on some newer (and hopefully better) style transfer AI models and once that's done I might come back to this plugin.

Merci de ta patience.

**Comment by Pixey1974** [comment]
Thank you for your reply.
